# Generated by Django 4.2.7 on 2025-10-04 08:33

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Food', 'Food'), ('Office Supplies', 'Office Supplies'), ('Other', 'Other')], default='Other', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=core.models.Expense.receipt_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='user_app.userdata')),
                ('paid_by', models.ForeignKey(blank=True, help_text='The person responsible for paying this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to='user_app.userdata')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='user_app.userdata')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.expense')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('manager_approval', models.BooleanField(default=False)),
                ('approval_sequence', models.BooleanField(default=False)),
                ('min_approval_percentage', models.IntegerField(default=51)),
                ('approvers', models.ManyToManyField(related_name='approver_approval_rules', to='user_app.userdata')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_approval_rules', to='user_app.userdata')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_approval_rules', to='user_app.userdata')),
            ],
        ),
    ]
